version: '3'

services:
  bpcapp:
    image: 931251277748.dkr.ecr.us-east-1.amazonaws.com/bpcapp:11.1.x
    volumes:
        - /volumes/green/javamelody:/tmp/javamelody
    environment:
      - BPC_DS_SERVER=green.interfacing.local
      - BPC_DS_PORT=1433
      - BPC_DS_DB=epc5
      - BPC_DS_USER=sa
      - BPC_DS_PASSWORD=5epc!ad
      - BPC_DS_UNICODE=true
      - BPC_EPC_URL=http://green.interfacing.local

  webapp:
    image: 931251277748.dkr.ecr.us-east-1.amazonaws.com/webapp:11.1.x

  nginx:
    image: 931251277748.dkr.ecr.us-east-1.amazonaws.com/nginx:11.1.x
    ports:
      - 8099:80
    volumes:
      - /volumes/green/nginx:/etc/nginx/shared-config

  search:
    image: 931251277748.dkr.ecr.us-east-1.amazonaws.com/search:11.1.x
    volumes:
        - /volumes/green/elasticsearch/data:/usr/share/elasticsearch/data

  unoconv:
    image: 931251277748.dkr.ecr.us-east-1.amazonaws.com/unoconv:11.1.x
